        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            CellPadding="4" DataKeyNames="i_id_department" DataSourceID="data" 
            ForeColor="#333333" GridLines="None" 
            OnRowUpdating="GridView2_RowUpdating">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="i_id_department" 
                    HeaderText="i_id_department" InsertVisible="False" 
                    ReadOnly="True" SortExpression="i_id_department" />
                <asp:BoundField DataField="vc_name" 
                    HeaderText="vc_name" SortExpression="vc_name" />
            </Columns>
            ...
        </asp:GridView>
        ...
        <asp:SqlDataSource ID="data" runat="server" ConnectionString="<%$ ConnectionStrings:db_connect %>" 
        // Select Command
        SelectCommand="SELECT [i_id_department], [vc_name] FROM [tbDepartments]" ConflictDetection="CompareAllValues" 
        // Delete Command
        DeleteCommand="DELETE FROM [tbDepartments] WHERE [i_id_department] = @original_i_id_department AND [vc_name] = @original_vc_name" 
        // Insert Command
        InsertCommand="INSERT INTO [tbDepartments] ([vc_name]) VALUES (@vc_name)" OldValuesParameterFormatString="original_{0}" 
        // Update Command
        UpdateCommand="UPDATE [tbDepartments] SET [vc_name] = @vc_name WHERE [i_id_department] = @original_i_id_department AND [vc_name] = @original_vc_name">
            <DeleteParameters>
                <asp:Parameter Name="original_i_id_department" Type="Int32" />
                <asp:Parameter Name="original_vc_name" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="vc_name" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="vc_name" Type="String" />
                <asp:Parameter Name="original_i_id_department" Type="Int32" />
                <asp:Parameter Name="original_vc_name" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>